namespace CommunityStats.Config;

/// <summary>
/// Simple i18n system for the mod. Supports English and Chinese.
/// All UI strings go through L.Get("key") to support language switching.
/// </summary>
public static class L
{
    public enum Lang { EN, CN }

    public static Lang Current { get; set; } = Lang.CN;

    public static string Get(string key) =>
        Current == Lang.CN
            ? (CN.TryGetValue(key, out var v) ? v : key)
            : (EN.TryGetValue(key, out var v2) ? v2 : key);

    // ── English ─────────────────────────────────────────────
    private static readonly Dictionary<string, string> EN = new()
    {
        // ContributionPanel
        ["contrib.title"] = "Contribution Stats",
        ["contrib.last_combat"] = "Last Combat",
        ["contrib.this_combat"] = "This Combat",
        ["contrib.run_summary"] = "Run Summary",
        ["contrib.vs"] = "vs",
        ["contrib.empty_combat"] = "No combat data yet — play a card to start tracking.",
        ["contrib.empty_run"] = "No run data yet — finish a combat to populate this tab.",

        // ContributionChart
        ["chart.damage"] = "Damage",
        ["chart.defense"] = "Defense",
        ["chart.draw"] = "Card Draw",
        ["chart.energy"] = "Energy Gained",
        ["chart.stars"] = "Stars",
        ["chart.healing"] = "Healing",
        ["chart.none"] = "  (none)",

        // FilterPanel / Settings
        ["settings.title"] = "Stats the Spire — Settings",
        ["settings.auto_asc"] = "Auto-match my Ascension",
        ["settings.min_asc"] = "Min Ascension:",
        ["settings.max_asc"] = "Max Ascension:",
        ["settings.min_wr"] = "Min Player Win%:",
        ["settings.version"] = "Version:",
        ["settings.ver_current"] = "Current",
        ["settings.ver_all"] = "All Versions",
        ["settings.sample"] = "Filtered data: {0} runs",
        ["settings.no_data"] = "No data loaded",
        ["settings.apply"] = "Apply",
        ["settings.upload"] = "Upload run data",
        ["settings.language"] = "Language:",
        // PRD §3.18 — character filter (F9 + CareerStats)
        ["settings.character"] = "Data Source (Character):",
        ["settings.char_auto"] = "Auto-match current",
        ["settings.char_all"] = "All Characters",
        ["char.IRONCLAD"] = "Ironclad",
        ["char.SILENT"] = "Silent",
        ["char.DEFECT"] = "Defect",
        ["char.NECROBINDER"] = "Necrobinder",
        ["char.REGENT"] = "Regent",

        // StatsLabel
        ["stats.pick"] = "Pick {0}% | Win {1}%",
        ["stats.relic"] = "Pick {0}% | Win {1}%",
        ["stats.event"] = "Chosen {0}% | Win {1}%",
        ["stats.event_pick"] = "Chosen {0}%",
        ["stats.encounter"] = "Death {0}% | Avg DMG {1}",
        ["stats.upgrade"] = "Upgrade {0}% | Win {1}%",
        ["stats.remove"] = "Remove {0}% | Win {1}%",
        ["stats.buy"] = "Buy {0}%",
        ["stats.loading"] = "Loading...",
        ["stats.no_data"] = "No data",

        // Unknown Room panel (§3.8)
        ["unknown.title"] = "Next [?] Room",
        ["unknown.subtitle"] = "Current encounter odds",
        ["unknown.relic_modified"] = "Modified by an active relic (e.g. Juzu Bracelet, Golden Compass)",
        ["room.event"] = "Event",
        ["room.monster"] = "Monster",
        ["room.elite"] = "Elite",
        ["room.treasure"] = "Treasure",
        ["room.shop"] = "Shop",

        // Potion drop odds (§3.9)
        ["potion.title"] = "Potion Drop (Next Combat)",
        ["settings.filter_section"] = "Ascension / Win Rate Filters",
        ["settings.close_to_apply"] = "Changes apply when you close this panel.",
        ["potion.subtitle"] = "Cumulative odds over N combats",
        ["potion.within"] = "Within {0} combats",
        ["potion.elite"] = "Elite combat drop",

        // Card drop odds (§3.17)
        ["carddrop.title"] = "Card Drops (Next Combat)",
        ["carddrop.subtitle"] = "Probability of at least one per rarity",
        ["carddrop.rare"] = "Rare",
        ["carddrop.uncommon"] = "Uncommon",
        ["carddrop.common"] = "Common",
        ["carddrop.col_regular"] = "Regular",
        ["carddrop.col_elite"] = "Elite",

        // Shop prices (§3.16)
        ["shop.title"] = "Shop Prices",
        ["shop.subtitle"] = "Merchant price table",
        ["shop.removal"] = "Remove a card: {0}",
        ["shop.relics"] = "Relics",
        ["shop.cards"] = "Cards",
        ["shop.potions"] = "Potions",
        ["shop.col_common"] = "Common",
        ["shop.col_uncommon"] = "Uncommon",
        ["shop.col_rare"] = "Rare",
        ["shop.discount_active"] = "Active discounts:",
        ["shop.colorless_note"] = "Colorless cards cost +15%",

        // Healing sources
        ["source.rest_site"] = "Rest Site",
        ["source.event"] = "Event",
        ["source.event_prefix"] = "[E] ",
        ["source.merchant"] = "Merchant",
        ["source.floor_regen"] = "Floor {0} Recovery",

        // Forge sub-bar labels (Regent's Sovereign Blade forge mechanic)
        ["source.forge_base"] = "Base Forge",
        ["source.forge_furnace"] = "Forge (Furnace)",
        ["source.forge_bulwark"] = "Forge (Bulwark)",
        ["source.forge_prefix"] = "Forge ({0})",

        // ModSettingsPatch
        ["mod.settings_btn"] = "Stats the Spire Settings",

        // Feature toggles (§3.14)
        ["toggle.contribution_panel"] = "Auto-open Contribution Panel after combat",
        ["toggle.card_library_stats"] = "Card Pick/Win Rate in Library",
        ["toggle.relic_stats"] = "Relic Win Rate / Delta Display",
        ["toggle.event_pick_rate"] = "Event Option Pick Rate",
        ["toggle.monster_danger"] = "Monster Room Danger Rating",
        ["toggle.unknown_room_odds"] = "Unknown Room Encounter Odds",
        ["toggle.shop_prices"] = "Shop Price Table",
        ["toggle.intent_state_machine"] = "Enemy Intent State Machine",

        // ContributionPanel v2 (§3.7, §4.5)
        ["contrib.dps"] = "Avg Damage per Turn:",
        ["contrib.help_title"] = "Stats the Spire — Help",
        ["contrib.help_body"] = "Bar colors: Cards (blue), Relics (gold), Potions (green)\nHotkeys: F8 Toggle Panel, F9 Settings\nDrag title bar to reposition.",
        ["contrib.help_section_colors"] = "Bar Color Legend",
        ["contrib.help_section_metrics"] = "Metric Definitions",
        ["contrib.help_color_card"] = "Card source",
        ["contrib.help_color_relic"] = "Relic source",
        ["contrib.help_color_potion"] = "Potion source",
        ["contrib.help_color_osty"] = "Osty (Necrobinder summon)",
        ["contrib.help_color_modifier"] = "Modifier bonus (Strength/Vulnerable/etc.)",
        ["contrib.help_color_attributed"] = "Attributed indirect damage (Poison/Burn ticks)",
        ["contrib.help_color_mitigate"] = "Mitigation (Weak debuff applied to enemy)",
        ["contrib.help_color_strdown"] = "Enemy strength reduction (Malaise/DarkShackles)",
        ["contrib.help_color_self"] = "Self damage (Offering/Bloodletting)",
        ["contrib.help_direct"] = "DirectDamage: HP removed by the card's own attack hit",
        ["contrib.help_modifier"] = "ModifierDamage: extra HP removed because of Strength / Inflame / Vajra etc. — credited to whichever source applied the modifier",
        ["contrib.help_attributed"] = "AttributedDamage: HP removed by power ticks (Poison, Burn, Caltrops) — credited to whichever card/relic applied that power",
        ["contrib.help_block"] = "EffectiveBlock: damage absorbed by Block stack belonging to the source card",
        ["contrib.help_mitigated"] = "MitigatedByDebuff/Buff: damage prevented by Weak / Buffer / Intangible — credited to whichever source applied that effect",
        ["contrib.help_str_reduce"] = "MitigatedByStrReduction: enemy attacks weakened because the source reduced enemy Strength",
        ["contrib.help_self"] = "SelfDamage: HP lost from Offering / Bloodletting / etc. Shown as a red bar but excluded from defense % so totals never exceed 100%.",
        ["contrib.help_energy"] = "EnergyGained: extra energy granted (or saved) by the source",
        ["contrib.help_heal"] = "HpHealed: HP restored or MaxHp gained credited to the source",
        ["contrib.help_draw"] = "CardsDrawn: extra cards drawn beyond the start-of-turn 5",
        ["contrib.help_stars"] = "StarsContribution: stars earned (Regent) credited to the source",
        ["contrib.help_dps"] = "DPS row = TotalDamageDealt ÷ TurnCount",
        ["contrib.help_pct"] = "Per-row % = source contribution ÷ total positive contributions of that section",
        ["contrib.help_source"] = "Data: live CombatTracker (this combat) + RunContributionAggregator (run summary)",
        ["contrib.help_hotkeys"] = "Hotkeys: F8 toggle panel, F9 settings, drag title bar to reposition",

        // Probability panels (§3.8, §3.9, §3.16, §3.17)
        ["prob.unknown_title"] = "Next [?] Room",
        ["prob.unknown_sub"] = "Current encounter odds",
        ["prob.event"] = "Event",
        ["prob.monster"] = "Monster",
        ["prob.elite"] = "Elite",
        ["prob.shop"] = "Shop",
        ["prob.treasure"] = "Treasure",
        ["prob.potion_title"] = "Potion Chance",
        ["prob.potion_sub"] = "Cumulative drop probability",
        ["prob.potion_within"] = "Within {0}",
        ["prob.card_title"] = "Card Drops (Next Combat)",
        ["prob.card_sub"] = "Probability of at least one",
        ["prob.normal"] = "Normal",
        ["prob.elite_col"] = "Elite",
        ["prob.rare"] = "Rare",
        ["prob.uncommon"] = "Uncommon",
        ["prob.common"] = "Common",
        ["prob.shop_title"] = "Shop Prices",
        ["prob.removal_cost"] = "Card Removal:",
        ["prob.discount_note"] = "50% sale, Colorless +15%",
        ["prob.cards"] = "Cards:",
        ["prob.relics"] = "Relics:",
        ["prob.potions"] = "Potions:",

        // Intent state machine (§3.10)
        ["intent.unavailable"] = "State machine data unavailable",
        ["intent.conditional"] = "conditional",

        // Career stats (§3.11)
        ["career.title"] = "Career Statistics",
        ["career.summary_title"] = "Summary",
        ["career.win_summary_card"] = "Win Rate",
        ["run_hist_btn"] = "Run Stats",
        ["run_hist_popup_title"] = "Run Statistics",
        ["career.ascension_n"] = "A{0}",
        ["career.ascension_all"] = "All Ascensions",
        ["career.asc_winloss"] = "{0} Wins/Losses",
        ["career.asc_winrate"] = "{0} Win Rate",
        ["career.min_ascension"] = "Min Ascension:",
        ["career.win_trend"] = "Win Rate Trend",
        // Round 9: column headers above ancient pool relic rows.
        ["career.col_pick_rate"] = "Pick Rate",
        ["career.col_pick_count"] = "Picks",
        ["career.col_win_rate"] = "Win Rate",
        ["career.col_delta"] = "Δ",
        ["career.last_n"] = "Last {0}",
        ["career.all"] = "All",
        ["career.death_causes"] = "Top Death Causes",
        ["career.path_stats"] = "Path Stats (per Act avg)",
        ["career.cards_gained"] = "Cards Obtained",
        ["career.cards_bought"] = "Cards Purchased",
        ["career.cards_removed"] = "Cards Removed",
        ["career.cards_upgraded"] = "Cards Upgraded",
        ["career.unknown_rooms"] = "? Rooms",
        ["career.monster_rooms"] = "Monster Fights",
        ["career.elite_rooms"] = "Elite Fights",
        ["career.shop_rooms"] = "Shops",
        ["career.campfire_rooms"] = "Campfires",
        ["career.asc_max_streak"] = "{0} Current/Best Streak",
        ["career.ancient_title"] = "Ancient Relic Pick Rate",
        ["career.boss_title"] = "Boss Damage Taken",
        ["career.avg_damage"] = "Avg Damage:",
        ["career.death_rate"] = "Death Rate:",
        ["career.pick_rate"] = "Pick Rate",
        ["career.times"] = "Times",
        ["career.win_rate"] = "Win Rate",
        ["career.delta"] = "Delta",
        ["career.loading"] = "Loading career data...",
        ["career.community_comparison"] = "Community Comparison",
        ["career.cause_abandoned"] = "Abandoned",
        ["career.act_n"] = "Act {0}",
        ["career.act_overgrowth"] = " (Overgrowth)",
        ["career.act_underdocks"] = " (Underdocks)",
        ["career.elder_select"] = "Select Elder",
        ["career.boss_select"] = "Select Boss",
        ["career.encounters"] = "encounters",
        ["career.no_data_short"] = "—",
        ["career.deck_section"] = "Deck Construction",
        ["career.path_section"] = "Path Stats",
        ["ancient.pool_1"] = "Option 1 Pool",
        ["ancient.pool_2"] = "Option 2 Pool",
        ["ancient.pool_3"] = "Option 3 Pool",
        ["ancient.pool_all"] = "Pool",
        ["ancient.positive_pool"] = "Positive Pool",
        ["ancient.curse_pool"] = "Curse Pool",
        ["ancient.act_only_n"] = "(Act {0} only)",
        ["ancient.shared_act"] = "Shared",
        ["card_lib.mine"] = "Mine",
        ["card_lib.community"] = "Community",
        ["card_lib.metric"] = "Metric",
        ["card_lib.samples"] = "Run Samples",
        ["card_lib.pick_rate"] = "Pick Rate",
        ["card_lib.win_rate"] = "Win Rate",
        ["card_lib.upgrade_rate"] = "Upgrade Rate",
        ["card_lib.removal_rate"] = "Removal Rate",
        ["card_lib.buy_rate"] = "Buy Rate",

        // Run History (§3.12)
        ["runhist.section_title"] = "Run Statistics",
        ["runhist.act_label"] = "Act {0}:",
        ["runhist.ancient_relic"] = "Ancient Relic:",
        ["runhist.ancient_picks"] = "Ancient Picks",
        ["runhist.boss_damage"] = "Boss Damage:",
        ["runhist.view_contrib"] = "View Contribution Chart",
        ["runhist.victory"] = "VICTORY",
        ["runhist.defeat"] = "DEFEAT",
        ["runhist.floors_n"] = "{0} floors",

        // Intent state machine (§3.10)
        ["intent.subtitle"] = "Intent State Machine",
        ["intent.current"] = "Current Intent",
        ["intent.no_move"] = "(no scheduled move)",
        ["intent.no_next"] = "(terminal state)",
        ["intent.state_machine"] = "Reachable States",
        ["intent.random"] = "(random)",

        // Filter panel additions (§3.13)
        ["settings.my_data"] = "Show my data only",
        ["settings.toggles_title"] = "Feature Toggles",

        // History import dialog (§3.19)
        ["import.dialog_title"] = "Upload Historical Runs",
        ["import.dialog_desc"] = "Would you like to upload your local run history to the community stats server? This helps build better community data.\n\nThis only happens once and runs in the background.",
        ["import.confirm"] = "Upload",
        ["import.skip"] = "Skip",
        ["import.progress"] = "Uploading data... ({0}/{1})",
        ["import.progress_done"] = "Upload complete ({0} runs)",
        ["upload.run_success"] = "Run uploaded ✓",
        ["upload.run_queued"] = "Upload queued (offline)",
        ["upload.run_rejected"] = "Upload rejected (server validation)",
    };

    // ── 中文 ────────────────────────────────────────────────
    private static readonly Dictionary<string, string> CN = new()
    {
        // ContributionPanel
        ["contrib.title"] = "战斗贡献统计",
        ["contrib.last_combat"] = "上场战斗",
        ["contrib.this_combat"] = "本场战斗",
        ["contrib.run_summary"] = "本局汇总",
        ["contrib.empty_combat"] = "暂无战斗数据 — 打出一张牌后开始追踪。",
        ["contrib.empty_run"] = "暂无本局数据 — 完成一场战斗后填充。",
        ["contrib.vs"] = "对战",

        // ContributionChart
        ["chart.damage"] = "伤害",
        ["chart.defense"] = "防御",
        ["chart.draw"] = "抽牌",
        ["chart.energy"] = "能量获取",
        ["chart.stars"] = "辉星",
        ["chart.healing"] = "治疗",
        ["chart.none"] = "  (无)",

        // FilterPanel / Settings
        ["settings.title"] = "Stats the Spire — 设置",
        ["settings.auto_asc"] = "自动匹配我的进阶",
        ["settings.min_asc"] = "最低进阶:",
        ["settings.max_asc"] = "最高进阶:",
        ["settings.min_wr"] = "最低玩家胜率:",
        ["settings.version"] = "版本:",
        ["settings.ver_current"] = "当前版本",
        ["settings.ver_all"] = "所有版本",
        ["settings.sample"] = "数据范围: {0} 局",
        ["settings.no_data"] = "未加载数据",
        ["settings.apply"] = "应用",
        ["settings.upload"] = "上传游玩数据",
        ["settings.language"] = "语言:",
        // PRD §3.18 — 角色筛选（F9 + 个人生涯统计）
        ["settings.character"] = "数据来源（角色）:",
        ["settings.char_auto"] = "自动匹配当前角色",
        ["settings.char_all"] = "所有角色",
        ["char.IRONCLAD"] = "铁甲战士",
        ["char.SILENT"] = "沉默猎手",
        ["char.DEFECT"] = "缺陷体",
        ["char.NECROBINDER"] = "亡灵契约师",
        ["char.REGENT"] = "储君",

        // StatsLabel
        ["stats.pick"] = "选取 {0}% | 胜率 {1}%",
        ["stats.relic"] = "选取 {0}% | 胜率 {1}%",
        ["stats.event"] = "选择 {0}% | 胜率 {1}%",
        ["stats.event_pick"] = "选择率 {0}%",
        ["stats.encounter"] = "死亡 {0}% | 平均伤害 {1}",
        ["stats.upgrade"] = "升级 {0}% | 胜率 {1}%",
        ["stats.remove"] = "移除 {0}% | 胜率 {1}%",
        ["stats.buy"] = "购买 {0}%",
        ["stats.loading"] = "加载中...",
        ["stats.no_data"] = "无数据",

        // Unknown Room panel (§3.8)
        ["unknown.title"] = "下一个 [?] 房间",
        ["unknown.subtitle"] = "当前遭遇概率",
        ["unknown.relic_modified"] = "已被遗物影响（如：佛珠手链、金罗盘）",
        ["room.event"] = "事件",
        ["room.monster"] = "怪物",
        ["room.elite"] = "精英",
        ["room.treasure"] = "宝箱",
        ["room.shop"] = "商店",

        // Potion drop odds (§3.9)
        ["potion.title"] = "药水掉落（下一场）",
        ["settings.filter_section"] = "进阶 / 胜率 筛选",
        ["settings.close_to_apply"] = "关闭此面板时自动应用更改。",
        ["potion.subtitle"] = "多场累计掉落概率",
        ["potion.within"] = "{0} 场内",
        ["potion.elite"] = "精英战掉落",

        // Card drop odds (§3.17)
        ["carddrop.title"] = "卡牌掉落(下一场)",
        ["carddrop.subtitle"] = "各稀有度至少出现一张的概率",
        ["carddrop.rare"] = "稀有",
        ["carddrop.uncommon"] = "罕见",
        ["carddrop.common"] = "普通",
        ["carddrop.col_regular"] = "普通战斗",
        ["carddrop.col_elite"] = "精英战斗",

        // Shop prices (§3.16)
        ["shop.title"] = "商店价格",
        ["shop.subtitle"] = "商店价格表",
        ["shop.removal"] = "删牌费用: {0}",
        ["shop.relics"] = "遗物",
        ["shop.cards"] = "卡牌",
        ["shop.potions"] = "药水",
        ["shop.col_common"] = "普通",
        ["shop.col_uncommon"] = "罕见",
        ["shop.col_rare"] = "稀有",
        ["shop.discount_active"] = "当前折扣：",
        ["shop.colorless_note"] = "无色牌价格 +15%",

        // Healing sources
        ["source.rest_site"] = "篝火休息",
        ["source.event"] = "事件",
        ["source.event_prefix"] = "[事件] ",
        ["source.merchant"] = "商店",
        ["source.floor_regen"] = "第{0}层恢复",

        // Forge sub-bar labels (储君之剑锻造机制子条)
        ["source.forge_base"] = "基础锻造",
        ["source.forge_furnace"] = "熔炉加成",
        ["source.forge_bulwark"] = "铸墙加成",
        ["source.forge_prefix"] = "锻造加成 ({0})",

        // ModSettingsPatch
        ["mod.settings_btn"] = "Stats the Spire 设置",

        // Feature toggles (§3.14)
        ["toggle.contribution_panel"] = "战斗结束后自动打开战斗贡献面板",
        ["toggle.card_library_stats"] = "卡牌选取率/胜率统计显示",
        ["toggle.relic_stats"] = "遗物胜率/胜率浮动显示",
        ["toggle.event_pick_rate"] = "事件选项选择率显示",
        ["toggle.monster_danger"] = "怪物房间危险度显示",
        ["toggle.unknown_room_odds"] = "问号房间遭遇概率显示",
        ["toggle.shop_prices"] = "商店价格显示",
        ["toggle.intent_state_machine"] = "敌人意图状态机显示",

        // ContributionPanel v2 (§3.7, §4.5)
        ["contrib.dps"] = "每回合平均伤害:",
        ["contrib.help_title"] = "Stats the Spire — 帮助",
        ["contrib.help_body"] = "柱状图颜色: 卡牌(蓝)、遗物(金)、药水(绿)\n打开/关闭快捷键: F8 ",
        ["contrib.help_section_colors"] = "条状图颜色图例",
        ["contrib.help_section_metrics"] = "贡献指标说明",
        ["contrib.help_color_card"] = "卡牌来源",
        ["contrib.help_color_relic"] = "遗物来源",
        ["contrib.help_color_potion"] = "药水来源",
        ["contrib.help_color_osty"] = "奥斯提（亡灵契约师召唤物）",
        ["contrib.help_color_modifier"] = "修正加成（力量 / 易伤 等）",
        ["contrib.help_color_attributed"] = "归因间接伤害（中毒 / 灾厄 等 状态触发）",
        ["contrib.help_color_mitigate"] = "减免（虚弱 等debuff）",
        ["contrib.help_color_strdown"] = "降低敌人力量",
        ["contrib.help_color_self"] = "自伤",
        ["contrib.help_direct"] = "直接伤害：卡牌本身打出造成的 HP 损失",
        ["contrib.help_modifier"] = "修正伤害：因力量/敏捷等修正而多出的伤害 — 归属到施加该修正的来源",
        ["contrib.help_attributed"] = "归因伤害：状态触发 (中毒、灾厄) 造成的伤害 — 归属到施加该 状态 的来源",
        ["contrib.help_block"] = "有效格挡：被来源卡的格挡叠加吸收的伤害",
        ["contrib.help_mitigated"] = "减免：被虚弱 / 缓冲 / 无实体 等阻挡的伤害 — 归属到施加该效果的来源",
        ["contrib.help_str_reduce"] = "降低敌人力量：因削减敌人力量而少受到的伤害 — 归属降低力量的来源",
        ["contrib.help_self"] = "自伤：献祭/放血等造成的 HP 损失。显示为红条但不计入防御 贡献百分比计算",
        ["contrib.help_energy"] = "能量获取：额外获得（或节省）的能量 — 归属到获取能量或节省能量的来源",
        ["contrib.help_heal"] = "HP 治疗：来源恢复 HP 或获得最大 HP，特别地，因最大 HP 提高而在每层的先古之民事件得到额外治疗也会计入",
        ["contrib.help_draw"] = "抽牌：超出回合开始 5 张以外的所有额外抽牌 — 归属抽牌的来源",
        ["contrib.help_stars"] = "辉星贡献：来源累积的辉星点数 — 归属获取辉星的来源",
        ["contrib.help_dps"] = "每回合伤害 = 总伤害 ÷ 回合数",
        ["contrib.help_pct"] = "每行 % = 该来源贡献 ÷ 该分区所有正向贡献之和",
        ["contrib.help_source"] = "数据来源：实时 CombatTracker（本场战斗）+ RunContributionAggregator（本局汇总）",
        ["contrib.help_hotkeys"] = "打开/关闭快捷键: F8",

        // Probability panels (§3.8, §3.9, §3.16, §3.17)
        ["prob.unknown_title"] = "下一个 [?] 房间",
        ["prob.unknown_sub"] = "当前遭遇概率",
        ["prob.event"] = "事件",
        ["prob.monster"] = "怪物",
        ["prob.elite"] = "精英",
        ["prob.shop"] = "商店",
        ["prob.treasure"] = "宝箱",
        ["prob.potion_title"] = "药水掉落概率",
        ["prob.potion_sub"] = "多场累计概率",
        ["prob.potion_within"] = "{0} 场内",
        ["prob.card_title"] = "卡牌掉落（下场战斗）",
        ["prob.card_sub"] = "至少出现一张的概率",
        ["prob.normal"] = "普通",
        ["prob.elite_col"] = "精英",
        ["prob.rare"] = "稀有",
        ["prob.uncommon"] = "非普通",
        ["prob.common"] = "普通",
        ["prob.shop_title"] = "商店价格",
        ["prob.removal_cost"] = "删牌费用:",
        ["prob.discount_note"] = "打折50%, 无色牌贵15%",
        ["prob.cards"] = "卡牌:",
        ["prob.relics"] = "遗物:",
        ["prob.potions"] = "药水:",

        // Intent state machine (§3.10)
        ["intent.unavailable"] = "状态机数据不可用",
        ["intent.conditional"] = "条件",

        // Career stats (§3.11)
        ["career.title"] = "个人生涯统计",
        ["career.summary_title"] = "数据汇总",
        ["career.win_summary_card"] = "胜率汇总",
        ["run_hist_btn"] = "本局统计",
        ["run_hist_popup_title"] = "本局统计",
        ["career.ascension_n"] = "进阶{0}",
        ["career.ascension_all"] = "全部进阶",
        ["career.asc_winloss"] = "{0} 胜利/失败",
        ["career.asc_winrate"] = "{0} 胜率",
        ["career.min_ascension"] = "最低进阶:",
        ["career.win_trend"] = "胜率趋势",
        // Round 9: column headers above ancient pool relic rows.
        ["career.col_pick_rate"] = "选取率",
        ["career.col_pick_count"] = "选取次数",
        ["career.col_win_rate"] = "胜率",
        ["career.col_delta"] = "胜率浮动",
        ["career.last_n"] = "最近 {0} 局",
        ["career.all"] = "全部",
        ["career.death_causes"] = "死因排行",
        ["career.path_stats"] = "路线统计（每 Act 平均）",
        ["career.cards_gained"] = "获取卡牌",
        ["career.cards_bought"] = "购买卡牌",
        ["career.cards_removed"] = "删除卡牌",
        ["career.cards_upgraded"] = "升级卡牌",
        ["career.unknown_rooms"] = "? 房间数",
        ["career.monster_rooms"] = "小怪战斗数",
        ["career.elite_rooms"] = "精英战斗数",
        ["career.shop_rooms"] = "商店数",
        ["career.campfire_rooms"] = "火堆数",
        ["career.asc_max_streak"] = "{0} 当前/最高连胜",
        ["career.ancient_title"] = "先古遗物选择率",
        ["career.boss_title"] = "Boss 战损",
        ["career.avg_damage"] = "平均战损:",
        ["career.death_rate"] = "死亡率:",
        ["career.pick_rate"] = "选择率",
        ["career.times"] = "次数",
        ["career.win_rate"] = "胜率",
        ["career.delta"] = "浮动",
        ["career.loading"] = "加载生涯数据中...",
        ["career.community_comparison"] = "社区对比",
        ["career.cause_abandoned"] = "中途放弃",
        ["career.act_n"] = "第{0}幕",
        ["career.act_overgrowth"] = "（密林）",
        ["career.act_underdocks"] = "（暗港）",
        ["career.elder_select"] = "选择先古之民",
        ["career.boss_select"] = "选择 Boss",
        ["career.encounters"] = "遭遇次数",
        ["career.no_data_short"] = "—",
        ["career.deck_section"] = "卡组构筑",
        ["career.path_section"] = "路线统计",
        ["ancient.pool_1"] = "选项一池",
        ["ancient.pool_2"] = "选项二池",
        ["ancient.pool_3"] = "选项三池",
        ["ancient.pool_all"] = "通用池",
        ["ancient.positive_pool"] = "正面遗物池",
        ["ancient.curse_pool"] = "诅咒遗物池",
        ["ancient.act_only_n"] = "（只在第{0}幕出现）",
        ["ancient.shared_act"] = "共享",
        ["card_lib.mine"] = "我的",
        ["card_lib.community"] = "社区",
        ["card_lib.metric"] = "指标",
        ["card_lib.samples"] = "对局样本数",
        ["card_lib.pick_rate"] = "选取率",
        ["card_lib.win_rate"] = "胜率",
        ["card_lib.upgrade_rate"] = "升级率",
        ["card_lib.removal_rate"] = "删除率",
        ["card_lib.buy_rate"] = "购买率",

        // Run History (§3.12)
        ["runhist.section_title"] = "本局统计",
        ["runhist.act_label"] = "第{0}幕：",
        ["runhist.ancient_relic"] = "先古遗物:",
        ["runhist.ancient_picks"] = "先古遗物选取",
        ["runhist.boss_damage"] = "Boss 战损:",
        ["runhist.view_contrib"] = "查看贡献图表",
        ["runhist.victory"] = "胜利",
        ["runhist.defeat"] = "失败",
        ["runhist.floors_n"] = "第{0}层",

        // Intent state machine (§3.10)
        ["intent.subtitle"] = "意图状态机",
        ["intent.current"] = "当前意图",
        ["intent.no_move"] = "(暂无意图)",
        ["intent.no_next"] = "(无后继状态)",
        ["intent.state_machine"] = "状态分支",
        ["intent.random"] = "(随机)",

        // Filter panel additions (§3.13)
        ["settings.my_data"] = "仅显示我的数据",
        ["settings.toggles_title"] = "功能开关",

        // History import dialog (§3.19)
        ["import.dialog_title"] = "上传历史记录",
        ["import.dialog_desc"] = "是否将你的本地历史对局数据上传至社区统计服务器？这有助于丰富社区数据。\n\n此操作仅执行一次，且在后台完成。",
        ["import.confirm"] = "确认上传",
        ["import.skip"] = "跳过",
        ["import.progress"] = "上传数据中... ({0}/{1})",
        ["import.progress_done"] = "上传完成 ({0} 局)",
        ["upload.run_success"] = "本局数据已上传 ✓",
        ["upload.run_queued"] = "上传已排队（离线）",
        ["upload.run_rejected"] = "上传被拒绝（服务器校验失败）",
    };
}
