using System;
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Entities.Multiplayer;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Helpers;
using MegaCrit.Sts2.Core.Logging;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Runs;

namespace MegaCrit.Sts2.Core.GameActions.Multiplayer;

/// <summary>
/// A player choice context for use in hooks that do not run as part of a GameAction.
/// When player choice is required, a new game action is created and enqueued directly to the player's action queue. From
/// there, flow proceeds like a normal game action. No game action is created if player choice is not requested.
/// </summary>
public class HookPlayerChoiceContext : PlayerChoiceContext
{
	private readonly ulong _localPlayerId;

	private GenericHookGameAction? _gameAction;

	private readonly TaskCompletionSource _taskAssignedCompletionSource = new TaskCompletionSource();

	private readonly TaskCompletionSource _pausedBeforeTaskAssignedCompletionSource = new TaskCompletionSource();

	private readonly TaskCompletionSource _pausedCompletionSource = new TaskCompletionSource();

	private ActionQueueSynchronizer? _actionQueueSynchronizer;

	private ActionQueueSet? _actionQueueSet;

	private ActionExecutor? _actionExecutor;

	/// <summary>
	/// The GameActionType to assign to the GameAction generated by this context, if any. Currently, only Combat and
	/// CombatPlayPhaseOnly are supported.
	/// Many hooks can execute outside of the player turn. For example, we allow the following:
	///  - Centennial Puzzle triggers on the enemy turn
	///  - Hellraiser triggers Seeker Strike
	///  - Seeker Strike causes a player choice
	/// However, for actions that start just before the player turn, we must wait until the player turn before executing
	/// them. Otherwise, we may run into ordering issues on remote players. For full context, see the
	/// HookPlayerChoiceContextTest.
	/// </summary>
	private GameActionType _gameActionType;

	private ActionQueueSynchronizer ActionQueueSynchronizer => _actionQueueSynchronizer ?? RunManager.Instance.ActionQueueSynchronizer;

	private ActionQueueSet ActionQueueSet => _actionQueueSet ?? RunManager.Instance.ActionQueueSet;

	private ActionExecutor ActionExecutor => _actionExecutor ?? RunManager.Instance.ActionExecutor;

	public AbstractModel? Source { get; }

	public Task? Task { get; private set; }

	public Player? Owner { get; }

	public GenericHookGameAction? GameAction => _gameAction;

	public HookPlayerChoiceContext(Player owner, ulong localPlayerId, GameActionType gameActionType)
	{
		_gameActionType = gameActionType;
		_localPlayerId = localPlayerId;
		Owner = owner;
	}

	public HookPlayerChoiceContext(AbstractModel source, ulong localPlayerId, ICombatState combatState, GameActionType gameActionType)
	{
		_localPlayerId = localPlayerId;
		Source = source;
		AbstractModel source2 = Source;
		Owner = ((source2 is CardModel cardModel) ? cardModel.Owner : ((source2 is RelicModel relicModel) ? relicModel.Owner : ((source2 is PotionModel potionModel) ? potionModel.Owner : ((source2 is AfflictionModel afflictionModel) ? afflictionModel.Card.Owner : ((!(source2 is EnchantmentModel enchantmentModel)) ? null : enchantmentModel.Card.Owner)))));
		if (Source is PowerModel powerModel)
		{
			if (powerModel.Owner.IsPlayer)
			{
				Owner = powerModel.Owner.Player;
			}
			else
			{
				Owner = combatState.Players[0];
			}
		}
		PushModel(Source);
		_gameActionType = gameActionType;
	}

	public void MockDependenciesForTest(ActionQueueSynchronizer? actionQueueSynchronizer, ActionQueueSet? actionQueueSet, ActionExecutor? actionExecutor)
	{
		_actionQueueSet = actionQueueSet;
		_actionQueueSynchronizer = actionQueueSynchronizer;
		_actionExecutor = actionExecutor;
	}

	/// <summary>
	/// Most hooks take a PlayerChoiceContext as an argument and return a Task. However, this player choice context must
	/// know about the task in SignalPlayerChoiceBegun, when it is time to create a GameAction. There is no way to pass
	/// the Task to this method in the constructor, as the Task is not created yet. Thus, this method should be called
	/// after the hook returns the Task, for two reasons:
	/// - To assign the Task to this context
	/// - To wait for the synchronous parts of the hook to complete
	/// </summary>
	/// <returns>True if the task was completed, false if it was paused.</returns>
	public async Task<bool> AssignTaskAndWaitForPauseOrCompletion(Task task)
	{
		if (Source != null)
		{
			Task = ExecuteTaskThenInvokeExecutionFinished(task);
		}
		else
		{
			Task = task;
		}
		_taskAssignedCompletionSource.SetResult();
		await TaskHelper.WhenAny(task, _pausedCompletionSource.Task);
		return task.IsCompleted;
	}

	/// <summary>
	/// ONLY USE THIS IF YOU KNOW WHAT YOU'RE DOING!
	/// This waits for the task to complete, _or_ for some content in the task to call SignalPlayerChoiceBegun.
	/// In most cases, AssignTaskAndWaitForPauseOrCompletion should be used. This should only be used when we don't yet
	/// have the full task to assign to the GameAction that would be generated during SignalPlayerChoiceBegun.
	/// </summary>
	/// <returns>True if the task was completed, false if it was paused.</returns>
	public async Task<bool> WaitForPauseOrCompletionWithoutAssigningTask(Task task)
	{
		await TaskHelper.WhenAny(task, _pausedBeforeTaskAssignedCompletionSource.Task);
		return task.IsCompleted;
	}

	/// <summary>
	/// At the end of all hooks that involve models, the ExecutionFinished event must be executed to update some visuals
	/// for things that are listening to changes to the model. This task wraps the hook and calls ExecutionFinished at
	/// the end of it, if a model is involved with the hook.
	/// </summary>
	private async Task ExecuteTaskThenInvokeExecutionFinished(Task task)
	{
		await task;
		Source?.InvokeExecutionFinished();
	}

	public override async Task SignalPlayerChoiceBegun(PlayerChoiceOptions options)
	{
		if (_gameAction != null)
		{
			if (ActionExecutor.CurrentlyRunningAction != _gameAction)
			{
				Log.Error($"Tried to interrupt action {_gameAction} but the currently running action is {ActionExecutor.CurrentlyRunningAction}!");
				return;
			}
		}
		else
		{
			if (Owner == null)
			{
				throw new InvalidOperationException($"HookPlayerChoiceContext is assigned a model {Source} with no owner, but the model has requested a player choice! This is not supported");
			}
			_gameAction = ActionQueueSynchronizer.GenerateHookAction(Owner.NetId, _gameActionType);
			_pausedBeforeTaskAssignedCompletionSource.SetResult();
			if (Task == null)
			{
				await _taskAssignedCompletionSource.Task;
				if (Task == null)
				{
					throw new InvalidOperationException("HookPlayerChoiceContext was never passed a task to await!");
				}
			}
			_gameAction.SetChoiceContext(this);
			if (_gameAction.OwnerId == _localPlayerId)
			{
				ActionQueueSynchronizer.RequestEnqueueHookAction(_gameAction);
			}
			_pausedCompletionSource.SetResult();
			await _gameAction.ExecutionStartedTask;
		}
		ActionQueueSet.PauseActionForPlayerChoice(_gameAction, options);
	}

	public override async Task SignalPlayerChoiceEnded()
	{
		if (_gameAction.OwnerId == _localPlayerId)
		{
			ActionQueueSynchronizer.RequestResumeActionAfterPlayerChoice(_gameAction);
		}
		await _gameAction.WaitForActionToResumeExecutingAfterPlayerChoice();
	}

	public async Task WaitForCompletion()
	{
		if (Task == null)
		{
			throw new InvalidOperationException("Tried to call WaitForCompletion before AssignTaskAndWaitForPauseOrCompletion was called!");
		}
		await Task;
		if (GameAction != null)
		{
			await GameAction.CompletionTask;
		}
	}
}
