namespace MegaCrit.Sts2.Core.Entities.Models;

public enum PlayerChoiceType
{
	None,
	/// <summary>
	/// For when the player is choosing from a set of canonical cards, like the cards generated by Attack Potion.
	/// </summary>
	CanonicalCard,
	/// <summary>
	/// For when the player is choosing from a set of mutable cards in a combat pile, like the cards in your hand when
	/// you play Survivor.
	/// </summary>
	CombatCard,
	/// <summary>
	/// For when the player is choosing from a set of mutable cards in a player's deck, like when you choose the Smith
	/// option at a rest site.
	/// </summary>
	DeckCard,
	/// <summary>
	/// For when the player is choosing from a set of mutable cards.
	/// Should be used any time we want the player to choose from a set of cards that may be modified from their
	/// canonical version (like if they're upgraded or enchanted).
	/// </summary>
	MutableCard,
	/// <summary>
	/// For when the player is targeting players outside of combat, and the decision point is synced.
	/// </summary>
	Player,
	/// <summary>
	/// For when the player is choosing an option out of a deterministically generated list of options.
	/// </summary>
	Index
}
