using System.Collections.Generic;
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;

namespace MegaCrit.Sts2.Core.Commands;

public static class RewardsCmd
{
	/// <summary>
	/// Offers rewards generated for the end of a combat or treasure room.
	/// If the player is not the local player, nothing happens.
	/// The rewards screen generated by this cmd will show the proceed button after all rewards are taken, and all input
	/// into the room will be blocked.
	/// </summary>
	/// <param name="player">The player to whom we are offering rewards.</param>
	/// <param name="room">The room to generate rewards for.</param>
	public static async Task OfferForRoomEnd(Player player, AbstractRoom room)
	{
		RewardsSet rewardsSet;
		if (room is CombatRoom combatRoom)
		{
			EncounterModel encounter = combatRoom.Encounter;
			if (encounter != null && !encounter.ShouldGiveRewards)
			{
				rewardsSet = new RewardsSet(player).EmptyForRoom(room);
				goto IL_00b4;
			}
		}
		rewardsSet = new RewardsSet(player).WithRewardsFromRoom(room);
		goto IL_00b4;
		IL_00b4:
		await rewardsSet.Offer();
	}

	/// <summary>
	/// Offers a custom set of rewards, usually from a relic or event.
	/// If the player is not the local player, nothing happens.
	/// The rewards may be changed by hooks, like Molten Egg or Ruby Earrings.
	/// The rewards screen generated by this cmd will not show the proceed button after all rewards are taken. The
	/// rewards screen will disappear and the player will be allowed to click into the room again.
	/// </summary>
	/// <param name="player">The player to whom we are offering rewards.</param>
	/// <param name="rewards">The list of rewards to offer the player.</param>
	public static async Task OfferCustom(Player player, List<Reward> rewards)
	{
		await new RewardsSet(player).WithCustomRewards(rewards).Offer();
	}

	/// <summary>
	/// Same as <see cref="M:MegaCrit.Sts2.Core.Commands.RewardsCmd.OfferForRoomEnd(MegaCrit.Sts2.Core.Entities.Players.Player,MegaCrit.Sts2.Core.Rooms.AbstractRoom)" />, except the rewards are not offered to the player.
	/// </summary>
	public static async Task<RewardsSet> GenerateForRoomEnd(Player player, AbstractRoom room)
	{
		RewardsSet set = new RewardsSet(player).WithRewardsFromRoom(room);
		await set.GenerateWithoutOffering();
		return set;
	}

	/// <summary>
	/// Same as <see cref="M:MegaCrit.Sts2.Core.Commands.RewardsCmd.OfferCustom(MegaCrit.Sts2.Core.Entities.Players.Player,System.Collections.Generic.List{MegaCrit.Sts2.Core.Rewards.Reward})" />, except the rewards are not offered to the player.
	/// </summary>
	public static async Task<RewardsSet> GenerateCustom(Player player, List<Reward> rewards)
	{
		RewardsSet set = new RewardsSet(player).WithCustomRewards(rewards);
		await set.GenerateWithoutOffering();
		return set;
	}
}
