using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Entities.Multiplayer;

namespace MegaCrit.Sts2.Core.Multiplayer.Game.Lobby;

/// <summary>
/// Handles callbacks generated by the <see cref="T:MegaCrit.Sts2.Core.Multiplayer.Game.Lobby.LoadRunLobby" />.
/// </summary>
public interface ILoadRunLobbyListener
{
	/// <summary>
	/// Called when a new player has connected. This includes the local player (even the host).
	/// If we are a client newly connecting to a host, and there are already players in the lobby, then this is called
	/// once for each player that is already in the lobby.
	/// </summary>
	/// <param name="playerId">The ID of the newly connected player.</param>
	void PlayerConnected(ulong playerId);

	/// <summary>
	/// Called when another player has left the lobby.
	/// </summary>
	/// <param name="playerId">The ID of the player who has left.</param>
	void RemotePlayerDisconnected(ulong playerId);

	/// <summary>
	/// Called when everyone is ready on the host. If this returns true, then the run will begin. Otherwise, the host
	/// will be un-readied and the run will not begin until the host re-readies.
	/// </summary>
	Task<bool> ShouldAllowRunToBegin();

	/// <summary>
	/// Called when the run begins, on both host and client. When calling CloseAndBeginRun on the host, you should
	/// wait for this call to actually begin the run.
	/// </summary>
	void BeginRun();

	/// <summary>
	/// Called when a player readies or un-readies.
	/// </summary>
	void PlayerReadyChanged(ulong playerId);

	/// <summary>
	/// Called when the local player has been disconnected from the lobby.
	/// <param name="info">Information about why we were disconnected.</param>
	/// </summary>
	void LocalPlayerDisconnected(NetErrorInfo info);
}
