using MegaCrit.Sts2.Core.Entities.Multiplayer;
using MegaCrit.Sts2.Core.Multiplayer.Messages.Lobby;

namespace MegaCrit.Sts2.Core.Multiplayer.Game.Lobby;

/// <summary>
/// Handles callbacks generated by the <see cref="T:MegaCrit.Sts2.Core.Multiplayer.Game.Lobby.RunLobby" />.
/// </summary>
public interface IRunLobbyListener
{
	/// <summary>
	/// Called when a player is attempting to rejoin the game.
	/// This should return a fully-filled ClientRejoinResponseMessage with the current game state.
	/// </summary>
	ClientRejoinResponseMessage GetRejoinMessage();

	/// <summary>
	/// Called when the local player has been disconnected from the lobby.
	/// </summary>
	void LocalPlayerDisconnected(NetErrorInfo info);

	/// <summary>
	/// Called when the run has been abandoned by the host.
	/// Note that LocalPlayerDisconnected will still be called in this case with NetError.Quit.
	/// </summary>
	void RunAbandoned();
}
