using System.Collections.Generic;
using MegaCrit.Sts2.Core.Entities.Multiplayer;
using MegaCrit.Sts2.Core.Models;

namespace MegaCrit.Sts2.Core.Multiplayer.Game.Lobby;

/// <summary>
/// Handles callbacks generated by the <see cref="T:MegaCrit.Sts2.Core.Multiplayer.Game.Lobby.StartRunLobby" />.
/// </summary>
public interface IStartRunLobbyListener
{
	/// <summary>
	/// Called when a new player has connected. This includes the local player (even the host).
	/// </summary>
	/// <param name="player">The newly connected player.</param>
	void PlayerConnected(LobbyPlayer player);

	/// <summary>
	/// Called when a lobby player's state has changed (e.g. their chosen character has changed).
	/// </summary>
	/// <param name="player">The player whose state has changed.</param>
	/// <param name="isRandomCharacterResolution">This is only set to true when the player has changed due to the lobby
	/// resolving the random character to the real one when the run is beginning.</param>
	void PlayerChanged(LobbyPlayer player, bool isRandomCharacterResolution);

	/// <summary>
	/// Called when the host has changed the ascension level, on both host and client.
	/// </summary>
	void AscensionChanged();

	/// <summary>
	/// Called when the host has changed the custom seed, on both host and client.
	/// </summary>
	void SeedChanged();

	/// <summary>
	/// Called when the host has changed the modifiers, on both host and client.
	/// </summary>
	void ModifiersChanged();

	/// <summary>
	/// Called when a client joins with a lower max ascension level than the previous one, on both host and client.
	/// Also called when the character changes in a singleplayer game, changing the max ascension.
	/// </summary>
	void MaxAscensionChanged();

	/// <summary>
	/// Called when another player has left the lobby.
	/// </summary>
	/// <param name="player">The player who has left.</param>
	void RemotePlayerDisconnected(LobbyPlayer player);

	/// <summary>
	/// Called when the run begins, on both host and client. When calling CloseAndBeginRun on the host, you should wait
	/// for this call to actually begin the run.
	/// </summary>
	/// <param name="seed">The seed used to start the run.</param>
	/// <param name="acts">The acts used to start the run.</param>
	/// <param name="modifiers">The modifiers used to start the run.</param>
	void BeginRun(string seed, List<ActModel> acts, IReadOnlyList<ModifierModel> modifiers);

	/// <summary>
	/// Called when the local player has been disconnected from the lobby.
	/// <param name="info">Information about why we were disconnected.</param>
	/// </summary>
	void LocalPlayerDisconnected(NetErrorInfo info);
}
