using System;
using System.Collections.Generic;
using System.Reflection;
using MegaCrit.Sts2.Core.Logging;

namespace MegaCrit.Sts2.Core.Saves.Migrations;

/// <summary>
/// Registry for save migrations.
/// This class will eventually be auto-generated by a source generator.
/// </summary>
/// <remarks>
/// IMPORTANT: This is a temporary reflection-based implementation.
/// Eventually, this class will be generated at compile time by a source generator
/// that scans for all classes with the [Migration] attribute.
/// </remarks>
public class MigrationRegistry
{
	public Dictionary<Type, List<IMigration>> Migrations { get; } = new Dictionary<Type, List<IMigration>>();

	/// <summary>
	/// Registers all migrations with the migration manager.
	/// </summary>
	/// <param name="manager">The migration manager to register migrations with</param>
	public void RegisterAllMigrations(MigrationManager manager)
	{
		try
		{
			Assembly assembly = typeof(IMigration).Assembly;
			Type typeFromHandle = typeof(IMigration);
			for (int i = 0; i < IMigrationSubtypes.Count; i++)
			{
				Type type = IMigrationSubtypes.Get(i);
				try
				{
					object obj = Activator.CreateInstance(type);
					if (obj is IMigration migration)
					{
						manager.RegisterMigration(migration);
						Log.Debug($"Registered migration for {migration.SaveType.Name} from v{migration.FromVersion} to v{migration.ToVersion}");
					}
					else
					{
						Log.Error("Failed to instantiate migration " + type.Name + ": Created instance is not an IMigration");
					}
				}
				catch (Exception ex)
				{
					Log.Error("Failed to instantiate migration " + type.Name + ": " + ex.Message);
				}
			}
			Log.Info($"Registered {IMigrationSubtypes.Count} migrations");
		}
		catch (Exception ex2)
		{
			Log.Error("Error registering migrations: " + ex2.Message);
		}
	}
}
